<?php

/**
 * Redirects to REA platform and does an autologin
 * Output example: https://https://ecosistema.buap.mx/rea/autologin/NSS000000/users.index
 * 
 */

use App\Models\Subject;

if (!function_exists('external_route')) {
    function external_route(string $route)
    {
        return getenv('SUBJECTS_BASE_URL')
            . "/redirect"
            . "?route="
            . $route;
    }
}

/**
 * 
 * 
 */
if (!function_exists('value_pairs')) {
    function value_pairs(string $name = null)
    {
        $collection = collect([
            'languages' => [
                [
                    'stored_value' => 'gsg',
                    'displayed_value' => 'Alemán'
                ],
                [
                    'stored_value' => 'spa',
                    'displayed_value' => 'Español'
                ],
                [
                    'stored_value' => 'fre',
                    'displayed_value' => 'Francés'
                ],
                [
                    'stored_value' => 'eng',
                    'displayed_value' => 'Inglés'
                ],
                [
                    'stored_value' => 'ita',
                    'displayed_value' => 'Italiano'
                ],
                [
                    'stored_value' => 'por',
                    'displayed_value' => 'Portugués'
                ],
            ],
            'genero' => [
                ['stored_value' => 'Autoevaluación / Self assessment', 'displayed_value' => 'Autoevaluación / Self assessment'],
                ['stored_value' => 'Caso / Case', 'displayed_value' => 'Caso / Case'],
                ['stored_value' => 'Conferencia / Lecture', 'displayed_value' => 'Conferencia / Lecture'],
                ['stored_value' => 'Cuestionario / questionnaire', 'displayed_value' => 'Cuestionario / questionnaire'],
                ['stored_value' => 'Diagrama / Diagram', 'displayed_value' => 'Diagrama / Diagram'],
                ['stored_value' => 'Diapositivas / Slides', 'displayed_value' => 'Diapositivas / Slides'],
                ['stored_value' => 'Ejercicio / Exercise', 'displayed_value' => 'Ejercicio / Exercise'],
                ['stored_value' => 'Exámen / Exam', 'displayed_value' => 'Exámen / Exam'],
                ['stored_value' => 'Experimento / Experiment', 'displayed_value' => 'Experimento / Experiment'],
                ['stored_value' => 'Figura / Figure', 'displayed_value' => 'Figura / Figure'],
                ['stored_value' => 'Gráfico / Graph', 'displayed_value' => 'Gráfico / Graph'],
                ['stored_value' => 'Índice / Index', 'displayed_value' => 'Índice / Index'],
                ['stored_value' => 'Planteamiento de problema / Problem statement', 'displayed_value' => 'Planteamiento de problema / Problem statement'],
                ['stored_value' => 'Rúbrica / Heading', 'displayed_value' => 'Rúbrica / Heading'],
                ['stored_value' => 'Simulación / Simulation', 'displayed_value' => 'Simulación / Simulation'],
                ['stored_value' => 'Tabla / Table', 'displayed_value' => 'Tabla / Table'],
                ['stored_value' => 'Texto narrativo / Narrative text', 'displayed_value' => 'Texto narrativo / Narrative text'],
                ['stored_value' => 'Resumen / Abstract', 'displayed_value' => 'Resumen / Abstract'],
                ['stored_value' => 'Reporte / Report', 'displayed_value' => 'Reporte / Report'],
                ['stored_value' => 'Ensayo /Essay', 'displayed_value' => 'Ensayo /Essay'],
                ['stored_value' => 'Reseña / Review', 'displayed_value' => 'Reseña / Review'],
                ['stored_value' => 'Libro / Book', 'displayed_value' => 'Libro / Book'],
                ['stored_value' => 'Curso / Course', 'displayed_value' => 'Curso / Course'],
                ['stored_value' => 'Lineamientos / Guidelines', 'displayed_value' => 'Lineamientos / Guidelines'],
            ],
            'estrategia' => [
                [
                    'stored_value' => 'Recurso Educativo Abierto',
                    'displayed_value' => 'Recurso Educativo Abierto'
                ], [
                    'stored_value' => 'Planeación didáctica',
                    'displayed_value' => 'Planeación didáctica',
                ]
            ],
            'estructura' => [
                [
                    'stored_value' => 'atómica',
                    'displayed_value' => 'atómica',
                ],
                [
                    'stored_value' => 'colección',
                    'displayed_value' => 'colección',
                ],
                [
                    'stored_value' => 'en red',
                    'displayed_value' => 'en red',
                ],
                [
                    'stored_value' => 'jerárquica',
                    'displayed_value' => 'jerárquica',
                ],
                [
                    'stored_value' => 'lineal',
                    'displayed_value' => 'lineal',
                ],
            ],
            'agregación' => [
                ['stored_value' => 'Nivel 1', 'displayed_value' => 'Nivel 1'],
                ['stored_value' => 'Nivel 2', 'displayed_value' => 'Nivel 2'],
                ['stored_value' => 'Nivel 3', 'displayed_value' => 'Nivel 3'],
                ['stored_value' => 'Nivel 4', 'displayed_value' => 'Nivel 4'],
            ],
            'estado' => [
                ['stored_value' => 'borrador', 'displayed_value' => 'borrador'],
                ['stored_value' => 'final', 'displayed_value' => 'final'],
                ['stored_value' => 'revisado', 'displayed_value' => 'revisado'],
                ['stored_value' => 'no disponible', 'displayed_value' => 'no disponible'],
            ],
            'contributor' => [
                ['stored_value' => 'editor', 'displayed_value' => 'editor'],
                ['stored_value' => 'unknown', 'displayed_value' => 'unknown'],
                ['stored_value' => 'validator', 'displayed_value' => 'validator'],
                ['stored_value' => 'editor', 'displayed_value' => 'editor'],
                ['stored_value' => 'graphicalDesigner', 'displayed_value' => 'graphicalDesigner'],
                ['stored_value' => 'technicalImplementer', 'displayed_value' => 'technicalImplementer'],
                ['stored_value' => 'contentProvider', 'displayed_value' => 'contentProvider'],
                ['stored_value' => 'technicalValidator', 'displayed_value' => 'technicalValidator'],
                ['stored_value' => 'educationalValidator', 'displayed_value' => 'educationalValidator'],
                ['stored_value' => 'scriptWriter', 'displayed_value' => 'scriptWriter'],
                ['stored_value' => 'instructionalDesigner', 'displayed_value' => 'instructionalDesigner'],
                ['stored_value' => 'subjectMatterExpert', 'displayed_value' => 'subjectMatterExpert'],
                ['stored_value' => 'initiator', 'displayed_value' => 'initiator'],
                ['stored_value' => 'terminator', 'displayed_value' => 'terminator'],
            ],
            'facultad' => [
                ['stored_value' => 'Facultad de Administración', 'displayed_value' => 'Facultad de Administración'],
                ['stored_value' => 'Facultad de Comunicación', 'displayed_value' => 'Facultad de Comunicación'],
                ['stored_value' => 'Facultad de Contaduría Pública', 'displayed_value' => 'Facultad de Contaduría Pública'],
                ['stored_value' => 'Facultad de Economía', 'displayed_value' => 'Facultad de Economía'],
                ['stored_value' => 'Facultad de Arquitectura', 'displayed_value' => 'Facultad de Arquitectura'],
                ['stored_value' => 'Facultad de Ciencias de la Computación', 'displayed_value' => 'Facultad de Ciencias de la Computación'],
                ['stored_value' => 'Facultad de Ciencias de la Electrónica', 'displayed_value' => 'Facultad de Ciencias de la Electrónica'],
                ['stored_value' => 'Facultad de Ciencias Físico Matemáticas', 'displayed_value' => 'Facultad de Ciencias Físico Matemáticas'],
                ['stored_value' => 'Facultad de Ingeniería', 'displayed_value' => 'Facultad de Ingeniería'],
                ['stored_value' => 'Facultad de Ingeniería Química', 'displayed_value' => 'Facultad de Ingeniería Química'],
                ['stored_value' => 'Facultad de Medicina Veterinaria y Zootecnia', 'displayed_value' => 'Facultad de Medicina Veterinaria y Zootecnia'],
                ['stored_value' => 'Facultad de Ciencias Biológicas', 'displayed_value' => 'Facultad de Ciencias Biológicas'],
                ['stored_value' => 'Facultad de Ingeniería Agrohidraúlica', 'displayed_value' => 'Facultad de Ingeniería Agrohidraúlica'],
                ['stored_value' => 'Facultad de Ciencias Quimicas', 'displayed_value' => 'Facultad de Ciencias Quimicas'],
                ['stored_value' => 'Facultad de Enfermería', 'displayed_value' => 'Facultad de Enfermería'],
                ['stored_value' => 'Facultad de Estomatología', 'displayed_value' => 'Facultad de Estomatología'],
                ['stored_value' => 'Facultad de Medicina', 'displayed_value' => 'Facultad de Medicina'],
                ['stored_value' => 'Facultad de Artes', 'displayed_value' => 'Facultad de Artes'],
                ['stored_value' => 'Escuela de Artes Plásticas y Audiovisuales', 'displayed_value' => 'Escuela de Artes Plásticas y Audiovisuales'],
                ['stored_value' => 'Facultad de Derecho y Ciencias Sociales', 'displayed_value' => 'Facultad de Derecho y Ciencias Sociales'],
                ['stored_value' => 'Facultad de Filosofía y Letras', 'displayed_value' => 'Facultad de Filosofía y Letras'],
                ['stored_value' => 'Facultad de Lenguas', 'displayed_value' => 'Facultad de Lenguas'],
                ['stored_value' => 'Facultad de Psicología', 'displayed_value' => 'Facultad de Psicología'],
                ['stored_value' => 'Facultad de Cultura Física', 'displayed_value' => 'Facultad de Cultura Física'],
                ['stored_value' => 'Bachilleratos BUAP', 'displayed_value' => 'Bachilleratos BUAP'],
                ['stored_value' => 'Preparatorias BUAP', 'displayed_value' => 'Preparatorias BUAP'],
                ['stored_value' => 'Complejo Regional Centro', 'displayed_value' => 'Complejo Regional Centro'],
                ['stored_value' => 'Complejo Regional Sur', 'displayed_value' => 'Complejo Regional Sur'],
                ['stored_value' => 'Complejo Regional Mixteca', 'displayed_value' => 'Complejo Regional Mixteca'],
                ['stored_value' => 'Complejo Regional Nororiental ', 'displayed_value' => 'Complejo Regional Nororiental '],
                ['stored_value' => 'Complejo Regional Norte', 'displayed_value' => 'Complejo Regional Norte'],
                ['stored_value' => 'Dirección de Educación Superior', 'displayed_value' => 'Dirección de Educación Superior'],
                ['stored_value' => 'Técnico Medio Superior BUAP', 'displayed_value' => 'Técnico Medio Superior BUAP'],
            ],
            'creative_commons' => [
                ['stored_value' => 'http://creativecommons.org/licenses/by/4.0', 'displayed_value' => 'CC BY Atribución http://creativecommons.org/licenses/by/4.0'],
                ['stored_value' => 'http://creativecommons.org/licenses/by-nc/4.0', 'displayed_value' => 'CC BY-NC  Atribución-NoComercial http://creativecommons.org/licenses/by-nc/4.0'],
            ],
            'rights' => [
                ['stored_value' => 'openAccess', 'displayed_value' => 'Acceso Abierto'],
                ['stored_value' => 'restrictedAccess', 'displayed_value' => 'Restringido'],
            ],
            'tipo_interna' => [
                ['stored_value' => 'Aprendizaje activo', 'displayed_value' => 'Aprendizaje activo'],
                ['stored_value' => 'Aprendizaje expositivo', 'displayed_value' => 'Aprendizaje expositivo'],
                ['stored_value' => 'Combinado', 'displayed_value' => 'Combinado'],
            ],
            'tipo_re' => [
                ['displayed_value' => 'Media--Fotografía', 'stored_value' => 'Media--Fotografía'],
                ['displayed_value' => 'Media--Ilustración', 'stored_value' => 'Media--Ilustración'],
                ['displayed_value' => 'Media--Video', 'stored_value' => 'Media--Video'],
                ['displayed_value' => 'Media--Animación', 'stored_value' => 'Media--Animación'],
                ['displayed_value' => 'Media--Música', 'stored_value' => 'Media--Música'],
                ['displayed_value' => 'Media--Efecto sonoro', 'stored_value' => 'Media--Efecto sonoro'],
                ['displayed_value' => 'Media--Locución', 'stored_value' => 'Media--Locución'],
                ['displayed_value' => 'Media--Audio compuesto', 'stored_value' => 'Media--Audio compuesto'],
                ['displayed_value' => 'Media--Texto narrativo', 'stored_value' => 'Media--Texto narrativo'],
                ['displayed_value' => 'Media--Hipertexto', 'stored_value' => 'Media--Hipertexto'],
                ['displayed_value' => 'Media--Grafismo', 'stored_value' => 'Media--Grafismo'],
                ['displayed_value' => 'Media--Media Integrado', 'stored_value' => 'Media--Media Integrado'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Base de datos', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Base de datos'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Tabla', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Tabla'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Gráfico', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Gráfico'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Mapa conceptual', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Mapa conceptual'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Mapa de navegación', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Mapa de navegación'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Presentación multimedia', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Presentación multimedia'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Tutorial', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Tutorial'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Diccionario digital', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Diccionario digital'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Enciclopedia digital', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Enciclopedia digital'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Publicación digital periódica', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Publicación digital periódica'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Web/portal temático o corporativo', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Web/portal temático o corporativo'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Wiki', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Wiki'],
                ['displayed_value' => 'Sistema de representación de información y/o conocimiento--Weblog', 'stored_value' => 'Sistema de representación de información y/o conocimiento--Weblog'],
                ['displayed_value' => 'Aplicación informática--Herramienta de creación/edición multimedia', 'stored_value' => 'Aplicación informática--Herramienta de creación/edición multimedia'],
                ['displayed_value' => 'Aplicación informática--Herramienta de creación/edición web', 'stored_value' => 'Aplicación informática--Herramienta de creación/edición web'],
                ['displayed_value' => 'Aplicación informática--Herramienta de ofimática', 'stored_value' => 'Aplicación informática--Herramienta de ofimática'],
                ['displayed_value' => 'Aplicación informática--Herramienta de programación', 'stored_value' => 'Aplicación informática--Herramienta de programación'],
                ['displayed_value' => 'Aplicación informática--Herramienta de análisis/organización de información/conocimiento', 'stored_value' => 'Aplicación informática--Herramienta de análisis/organización de información/conocimiento'],
                ['displayed_value' => 'Aplicación informática--Herramienta de apoyo a procesos/procedimientos', 'stored_value' => 'Aplicación informática--Herramienta de apoyo a procesos/procedimientos'],
                ['displayed_value' => 'Aplicación informática--Herramienta de gestión de aprendizaje/trabajo individual/cooperativo/colaborativo', 'stored_value' => 'Aplicación informática--Herramienta de gestión de aprendizaje/trabajo individual/cooperativo/colaborativo'],
                ['displayed_value' => 'Servicio--Servicio de creación/edición multimedia', 'stored_value' => 'Servicio--Servicio de creación/edición multimedia'],
                ['displayed_value' => 'Servicio--Servicio de creación/edición web', 'stored_value' => 'Servicio--Servicio de creación/edición web'],
                ['displayed_value' => 'Servicio--Servicio de ofimática', 'stored_value' => 'Servicio--Servicio de ofimática'],
                ['displayed_value' => 'Servicio--Servicio de programación', 'stored_value' => 'Servicio--Servicio de programación'],
                ['displayed_value' => 'Servicio--Servicio de análisis/organización de información/conocimiento', 'stored_value' => 'Servicio--Servicio de análisis/organización de información/conocimiento'],
                ['displayed_value' => 'Servicio--Servicio de apoyo a procesos/procedimientos', 'stored_value' => 'Servicio--Servicio de apoyo a procesos/procedimientos'],
                ['displayed_value' => 'Servicio--Servicio de gestión de aprendizaje/trabajo individual/cooperativo/colaborativo', 'stored_value' => 'Servicio--Servicio de gestión de aprendizaje/trabajo individual/cooperativo/colaborativo'],
                ['displayed_value' => 'Contenido didáctico--Lecturas guiadas', 'stored_value' => 'Contenido didáctico--Lecturas guiadas'],
                ['displayed_value' => 'Contenido didáctico--Lección magistral', 'stored_value' => 'Contenido didáctico--Lección magistral'],
                ['displayed_value' => 'Contenido didáctico--Comentario de texto-imagen', 'stored_value' => 'Contenido didáctico--Comentario de texto-imagen'],
                ['displayed_value' => 'Contenido didáctico--Actividad de discusión', 'stored_value' => 'Contenido didáctico--Actividad de discusión'],
                ['displayed_value' => 'Contenido didáctico--Ejercicio o problema cerrado', 'stored_value' => 'Contenido didáctico--Ejercicio o problema cerrado'],
                ['displayed_value' => 'Contenido didáctico--Caso contextualizado', 'stored_value' => 'Contenido didáctico--Caso contextualizado'],
                ['displayed_value' => 'Contenido didáctico--Problema abierto', 'stored_value' => 'Contenido didáctico--Problema abierto'],
                ['displayed_value' => 'Contenido didáctico--Escenario real o virtual de aprendizaje', 'stored_value' => 'Contenido didáctico--Escenario real o virtual de aprendizaje'],
                ['displayed_value' => 'Contenido didáctico--Juego didáctico', 'stored_value' => 'Contenido didáctico--Juego didáctico'],
                ['displayed_value' => 'Contenido didáctico--Webquest', 'stored_value' => 'Contenido didáctico--Webquest'],
                ['displayed_value' => 'Contenido didáctico--Experimento', 'stored_value' => 'Contenido didáctico--Experimento'],
                ['displayed_value' => 'Contenido didáctico--Simulación', 'stored_value' => 'Contenido didáctico--Simulación'],
                ['displayed_value' => 'Contenido didáctico--Proyecto real', 'stored_value' => 'Contenido didáctico--Proyecto real'],
                ['displayed_value' => 'Contenido didáctico--Cuestionario', 'stored_value' => 'Contenido didáctico--Cuestionario'],
                ['displayed_value' => 'Contenido didáctico--Examen', 'stored_value' => 'Contenido didáctico--Examen'],
                ['displayed_value' => 'Contenido didáctico--Autoevaluación', 'stored_value' => 'Contenido didáctico--Autoevaluación'],
                ['displayed_value' => 'Contenido didáctico--Planeación didáctica', 'stored_value' => 'Contenido didáctico--Planeación didáctica'],
            ],
            'n_interact' => [
                ['stored_value' => 'muy bajo', 'displayed_value' => 'muy bajo'],
                ['stored_value' => 'bajo', 'displayed_value' => 'bajo'],
                ['stored_value' => 'medio', 'displayed_value' => 'medio'],
                ['stored_value' => 'alto', 'displayed_value' => 'alto'],
                ['stored_value' => 'muy alto', 'displayed_value' => 'muy alto'],
            ],
            'destinatario' => [
                ['stored_value' => 'Tipo de aprendiz--Alumnado', 'displayed_value' => 'Tipo de aprendiz--Alumnado'],
                ['stored_value' => 'Tipo de aprendiz--Alumnado con necesidades educativas especiales', 'displayed_value' => 'Tipo de aprendiz--Alumnado con necesidades educativas especiales'],
                ['stored_value' => 'Tipo de aprendiz--Alumnado con altas capacidades intelectuales', 'displayed_value' => 'Tipo de aprendiz--Alumnado con altas capacidades intelectuales'],
                ['stored_value' => 'Tipo de aprendiz--Alumnado con integración tardía en sistema educativo', 'displayed_value' => 'Tipo de aprendiz--Alumnado con integración tardía en sistema educativo'],
                ['stored_value' => 'Tipo de aprendiz--Alumnado con otras necesidades específicas de apoyo educativo', 'displayed_value' => 'Tipo de aprendiz--Alumnado con otras necesidades específicas de apoyo educativo'],
                ['stored_value' => 'Tipo de aprendiz--Público en general', 'displayed_value' => 'Tipo de aprendiz--Público en general'],
                ['stored_value' => 'Agrupamiento de los alumnos--Individual', 'displayed_value' => 'Agrupamiento de los alumnos--Individual'],
                ['stored_value' => 'Agrupamiento de los alumnos--Grupal', 'displayed_value' => 'Agrupamiento de los alumnos--Grupal'],
                ['stored_value' => 'Educador--Docente', 'displayed_value' => 'Educador--Docente'],
                ['stored_value' => 'Educador--Tutor', 'displayed_value' => 'Educador--Tutor'],
                ['stored_value' => 'Educador--Familia', 'displayed_value' => 'Educador--Familia'],
                ['stored_value' => 'Expertos--Documentalista', 'displayed_value' => 'Expertos--Documentalista'],
                ['stored_value' => 'Expertos--Informático', 'displayed_value' => 'Expertos--Informático'],
                ['stored_value' => 'Expertos--Administrador', 'displayed_value' => 'Expertos--Administrador'],
                ['stored_value' => 'Expertos--Experto en educación', 'displayed_value' => 'Expertos--Experto en educación'],
                ['stored_value' => 'Expertos--Experto en la materia', 'displayed_value' => 'Expertos--Experto en la materia'],
            ],
            'contexto' => [
                ['stored_value' => 'aula', 'displayed_value' => 'aula'],
                ['stored_value' => 'laboratorio', 'displayed_value' => 'laboratorio'],
                ['stored_value' => 'entorno real', 'displayed_value' => 'entorno real'],
                ['stored_value' => 'domicilio', 'displayed_value' => 'domicilio'],
                ['stored_value' => 'mixto', 'displayed_value' => 'mixto'],
                ['stored_value' => 'docente', 'displayed_value' => 'docente'],
                ['stored_value' => 'tutor', 'displayed_value' => 'tutor'],
                ['stored_value' => 'familia', 'displayed_value' => 'familia'],
                ['stored_value' => 'compañero', 'displayed_value' => 'compañero'],
                ['stored_value' => 'independiente', 'displayed_value' => 'independiente'],
                ['stored_value' => 'mixta', 'displayed_value' => 'mixta'],
                ['stored_value' => 'presencial', 'displayed_value' => 'presencial'],
                ['stored_value' => 'semipresencial', 'displayed_value' => 'semipresencial'],
                ['stored_value' => 'distancia                ', 'displayed_value' => 'distancia'],
            ],
            'p_cog' => [
                ['stored_value' => 'aula', 'displayed_value' => 'aula'],
                ['stored_value' => 'laboratorio', 'displayed_value' => 'laboratorio'],
                ['stored_value' => 'entorno real', 'displayed_value' => 'entorno real'],
                ['stored_value' => 'domicilio', 'displayed_value' => 'domicilio'],
                ['stored_value' => 'mixto', 'displayed_value' => 'mixto'],
                ['stored_value' => 'docente', 'displayed_value' => 'docente'],
                ['stored_value' => 'tutor', 'displayed_value' => 'tutor'],
                ['stored_value' => 'familia', 'displayed_value' => 'familia'],
                ['stored_value' => 'compañero', 'displayed_value' => 'compañero'],
                ['stored_value' => 'independiente', 'displayed_value' => 'independiente'],
                ['stored_value' => 'mixta', 'displayed_value' => 'mixta'],
                ['stored_value' => 'presencial', 'displayed_value' => 'presencial'],
                ['stored_value' => 'semipresencial', 'displayed_value' => 'semipresencial'],
                ['stored_value' => 'distancia', 'displayed_value' => 'distancia'],
            ],
            'relation_values' => [
                ['stored_value' => 'conformsTo', 'displayed_value' => 'Conforme a'],
                ['stored_value' => 'hasFormat', 'displayed_value' => 'Tiene Formato'],
                ['stored_value' => 'hasPart', 'displayed_value' => 'Tiene Parte de'],
                ['stored_value' => 'hasVersion', 'displayed_value' => 'Tiene Como Version'],
                ['stored_value' => 'isbasedon', 'displayed_value' => 'Está basado en'],
                ['stored_value' => 'isFormatOf', 'displayed_value' => 'Está en Formato'],
                ['stored_value' => 'isPartOf', 'displayed_value' => 'Es Parte de'],
                ['stored_value' => 'ispartofseries', 'displayed_value' => 'Es parte de la serie'],
                ['stored_value' => 'isreferencedby', 'displayed_value' => 'Está Citado Por'],
                ['stored_value' => 'isreplacedby', 'displayed_value' => 'Es Reemplazado Por'],
                ['stored_value' => 'isRequiredBy', 'displayed_value' => 'Es Requerido Por'],
                ['stored_value' => 'isVersionOf', 'displayed_value' => 'Es Versión De'],
                ['stored_value' => 'references', 'displayed_value' => 'Cita a'],
                ['stored_value' => 'replaces', 'displayed_value' => 'Reemplaza'],
                ['stored_value' => 'requires', 'displayed_value' => 'Requiere'],
            ],
            'accesibilidad' => [
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Auditivo (con voz o sonido)--Informativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Auditivo (con voz o sonido)--Informativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Auditivo (con voz o sonido)--Decorativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Auditivo (con voz o sonido)--Decorativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Auditivo (con voz o sonido)--Motivacional', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Auditivo (con voz o sonido)--Motivacional'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Táctil--Informativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Táctil--Informativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Táctil--Decorativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Táctil--Decorativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Táctil--Motivacional', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Táctil--Motivacional'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Textual (visual por texto)--Informativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Textual (visual por texto)--Informativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Textual (visual por texto)--Decorativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Textual (visual por texto)--Decorativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Textual (visual por texto)--Motivacional', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Textual (visual por texto)--Motivacional'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Visual (solo por icono) --Informativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Visual (solo por icono) --Informativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Visual (solo por icono) --Decorativo', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Visual (solo por icono) --Decorativo'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de presentación de la información en el acceso--Visual (solo por icono) --Motivacional', 'displayed_value' => 'Acceso al siguiente nivel--Modo de presentación--Visual (solo por icono) --Motivacional'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de interacción para el acceso--Por teclado --', 'displayed_value' => 'Acceso al siguiente nivel--Modo de interación----Por teclado'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de interacción para el acceso--Por ratón u otros dispositivos apuntadores --', 'displayed_value' => 'Acceso al siguiente nivel--Modo de interación----Por ratón u otros dispositivos apuntadores'],
                ['stored_value' => 'Declaración del modo de acceso al siguiente nivel--Modo de interacción para el acceso--Por reconocimiento de voz--', 'displayed_value' => 'Acceso al siguiente nivel--Modo de interación----Por reconocimiento de voz'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Auditivo (con voz o sonido)--Informativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Auditivo (con voz o sonido)--Informativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Auditivo (con voz o sonido)--Decorativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Auditivo (con voz o sonido)--Decorativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Auditivo (con voz o sonido)--Motivacional', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Auditivo (con voz o sonido)--Motivacional'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Táctil--Informativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Táctil--Informativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Táctil--Decorativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Táctil--Decorativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Táctil--Motivacional', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Táctil--Motivacional'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Textual (visual por texto)--Informativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Textual (visual por texto)--Informativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Textual (visual por texto)--Decorativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Textual (visual por texto)--Decorativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Textual (visual por texto)--Motivacional', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Textual (visual por texto)--Motivacional'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Visual (solo por icono) --Informativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Visual (solo por icono) --Informativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Visual (solo por icono) --Decorativo', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Visual (solo por icono) --Decorativo'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Visual (solo por icono) --Motivacional', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Visual (solo por icono) --Motivacional'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Permite control flexible--Si', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Permite control flexible--Si'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modo de presentación de la información dentro del objeto--Permite control flexible--No', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de presentación--Permite control flexible--No'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modos de interacción dentro de la actividad--Control total por teclado', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de interacción--Control total por teclado'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modos de interacción dentro de la actividad--Control total por ratón u otros dispositivos apuntadores (hardware específico, tableta)', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de interacción--Control total por ratón u otros dispositivos apuntadores (hardware específico, tableta)'],
                ['stored_value' => 'Declaración del modo de interacción en la actividad de aprendizaje--Modos de interacción dentro de la actividad--Control total por reconocimiento de voz', 'displayed_value' => 'Interacción en la actividad de aprendizaje--Modo de interacción--Control total por reconocimiento de voz'],
                ['stored_value' => 'Trabaja a pantalla completa--Si', 'displayed_value' => 'Trabaja a pantalla completa--Si'],
                ['stored_value' => 'Trabaja a pantalla completa--No', 'displayed_value' => 'Trabaja a pantalla completa--No'],
                ['stored_value' => 'Resolución de pantalla nativa--800x600', 'displayed_value' => 'Resolución de pantalla nativa--800x600'],
                ['stored_value' => 'Resolución de pantalla nativa--1024x768', 'displayed_value' => 'Resolución de pantalla nativa--1024x768'],
                ['stored_value' => 'Permite cambio de resolución con ajuste de contenido--Funciona con auto-ajuste', 'displayed_value' => 'Permite cambio de resolución con ajuste de contenido--Funciona con auto-ajuste'],
                ['stored_value' => 'Permite cambio de resolución con ajuste de contenido--Permite cambio de 800x600 a 1024 x768', 'displayed_value' => 'Permite cambio de resolución con ajuste de contenido--Permite cambio de 800x600 a 1024 x768'],
                ['stored_value' => 'Permite cambio de resolución con ajuste de contenido--Permite cambio de 1024x768 a 800x600', 'displayed_value' => 'Permite cambio de resolución con ajuste de contenido--Permite cambio de 1024x768 a 800x600'],
                ['stored_value' => 'Permite adaptar la visualización--Si', 'displayed_value' => 'Permite adaptar la visualización--Si'],
                ['stored_value' => 'Permite adaptar la visualización--No', 'displayed_value' => 'Permite adaptar la visualización--No'],
                ['stored_value' => 'Visualización adaptable--Tamaño caracteres', 'displayed_value' => 'Visualización adaptable--Tamaño caracteres'],
                ['stored_value' => 'Visualización adaptable--Tipo de fuente', 'displayed_value' => 'Visualización adaptable--Tipo de fuente'],
                ['stored_value' => 'Visualización adaptable--Color de fuente', 'displayed_value' => 'Visualización adaptable--Color de fuente'],
                ['stored_value' => 'Visualización adaptable--Color de fondo', 'displayed_value' => 'Visualización adaptable--Color de fondo'],
                ['stored_value' => 'Visualización adaptable--Formato cursor', 'displayed_value' => 'Visualización adaptable--Formato cursor'],
                ['stored_value' => 'Visualización adaptable--Formato selección', 'displayed_value' => 'Visualización adaptable--Formato selección'],
                ['stored_value' => 'Visualización adaptable--Estilo de plantilla', 'displayed_value' => 'Visualización adaptable--Estilo de plantilla'],
                ['stored_value' => 'Visualización adaptable--Estructura de presentación', 'displayed_value' => 'Visualización adaptable--Estructura de presentación'],
                ['stored_value' => 'Visualización adaptable--Tratamiento de la imagen (únicamente en los formatos en que esto sea posible)', 'displayed_value' => 'Visualización adaptable--Tratamiento de la imagen (únicamente en los formatos en que esto sea posible)'],
                ['stored_value' => 'Visualización adaptable--Contraste de imagen', 'displayed_value' => 'Visualización adaptable--Contraste de imagen'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Audio-descripción', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Audio-descripción'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Audio-descripción extendida', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Audio-descripción extendida'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Transcripción completa', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Transcripción completa'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Representación táctil', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Representación táctil'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Representación textual', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Representación textual'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Representación visual', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Representación visual'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Subtitulado', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Subtitulado'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Subtitulado para sordos', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Subtitulado para sordos'],
                ['stored_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Lenguaje de signo', 'displayed_value' => 'Declaración de adaptabilidad--Tipo de adaptación--Lenguaje de signo'],
                ['stored_value' => 'Tiene control del tiempo de ejecución--Si', 'displayed_value' => 'Tiene control del tiempo de ejecución--Si'],
                ['stored_value' => 'Tiene control del tiempo de ejecución--No', 'displayed_value' => 'Tiene control del tiempo de ejecución--No'],
                ['stored_value' => 'Tipo de contador de ejecución--Hacia delante modificable', 'displayed_value' => 'Tipo de contador de ejecución--Hacia delante modificable'],
                ['stored_value' => 'Tipo de contador de ejecución--Hacia delante no modificable', 'displayed_value' => 'Tipo de contador de ejecución--Hacia delante no modificable'],
                ['stored_value' => 'Tipo de contador de ejecución--Hacia atrás modificable', 'displayed_value' => 'Tipo de contador de ejecución--Hacia atrás modificable'],
                ['stored_value' => 'Tipo de contador de ejecución--Hacia atrás no modificable', 'displayed_value' => 'Tipo de contador de ejecución--Hacia atrás no modificable'],
            ],
            'nivel_e' => [
                ["stored_value" => "Educación especial--Educación Infantil", "displayed_value" => "Educación especial--Educación Infantil"],
                ["stored_value" => "Educación especial--Educación Primaria", "displayed_value" => "Educación especial--Educación Primaria"],
                ["stored_value" => "Educación especial--Educación Secundaria Obligatoria", "displayed_value" => "Educación especial--Educación Secundaria Obligatoria"],
                ["stored_value" => "Educación infantil--Primer ciclo--0 años", "displayed_value" => "Educación infantil--Primer ciclo--0 años"],
                ["stored_value" => "Educación infantil--Primer ciclo--1 año", "displayed_value" => "Educación infantil--Primer ciclo--1 año"],
                ["stored_value" => "Educación infantil--Primer ciclo--2 años", "displayed_value" => "Educación infantil--Primer ciclo--2 años"],
                ["stored_value" => "Educación infantil--Segundo ciclo--3 años", "displayed_value" => "Educación infantil--Segundo ciclo--3 años"],
                ["stored_value" => "Educación infantil--Segundo ciclo--4 años", "displayed_value" => "Educación infantil--Segundo ciclo--4 años"],
                ["stored_value" => "Educación infantil--Segundo ciclo--5 años", "displayed_value" => "Educación infantil--Segundo ciclo--5 años"],
                ["stored_value" => "Educación primaria--Primer ciclo--Primer curso", "displayed_value" => "Educación primaria--Primer ciclo--Primer curso"],
                ["stored_value" => "Educación primaria--Primer ciclo--Segundo ciclo", "displayed_value" => "Educación primaria--Primer ciclo--Segundo ciclo"],
                ["stored_value" => "Educación primaria--Segundo ciclo--Tercer curso", "displayed_value" => "Educación primaria--Segundo ciclo--Tercer curso"],
                ["stored_value" => "Educación primaria--Segundo ciclo--Cuarto curso", "displayed_value" => "Educación primaria--Segundo ciclo--Cuarto curso"],
                ["stored_value" => "Educación primaria--Tercer ciclo--Quinto curso", "displayed_value" => "Educación primaria--Tercer ciclo--Quinto curso"],
                ["stored_value" => "Educación primaria--Tercer ciclo--Sexto curso", "displayed_value" => "Educación primaria--Tercer ciclo--Sexto curso"],
                ["stored_value" => "Educación secundaria obigatoria--Primer curso", "displayed_value" => "Educación secundaria obigatoria--Primer curso"],
                ["stored_value" => "Educación secundaria obigatoria--Segundo ciclo", "displayed_value" => "Educación secundaria obigatoria--Segundo ciclo"],
                ["stored_value" => "Educación secundaria obigatoria--Tercer curso", "displayed_value" => "Educación secundaria obigatoria--Tercer curso"],
                ["stored_value" => "Educación secundaria obigatoria--Cuarto curso", "displayed_value" => "Educación secundaria obigatoria--Cuarto curso"],
                ["stored_value" => "Educación secundaria obigatoria--Diversificación curricular", "displayed_value" => "Educación secundaria obigatoria--Diversificación curricular"],
                ["stored_value" => "Enseñanza compensatoria--Aulas de enlace", "displayed_value" => "Enseñanza compensatoria--Aulas de enlace"],
                ["stored_value" => "Enseñanza compensatoria--Aulas de acogida", "displayed_value" => "Enseñanza compensatoria--Aulas de acogida"],
                ["stored_value" => "Enseñanza compensatoria--Aulas hospitalarias", "displayed_value" => "Enseñanza compensatoria--Aulas hospitalarias"],
                ["stored_value" => "Bachillerato", "displayed_value" => "Bachillerato"],
                ["stored_value" => "Programas de cualificación profesional inicial--Iniciación profesional", "displayed_value" => "Programas de cualificación profesional inicial--Iniciación profesional"],
                ["stored_value" => "Programas de cualificación profesional inicial--Formación empleo", "displayed_value" => "Programas de cualificación profesional inicial--Formación empleo"],
                ["stored_value" => "Programas de cualificación profesional inicial--Talleres profesionales", "displayed_value" => "Programas de cualificación profesional inicial--Talleres profesionales"],
                ["stored_value" => "Programas de cualificación profesional inicial--Iniciación profesional especial", "displayed_value" => "Programas de cualificación profesional inicial--Iniciación profesional especial"],
                ["stored_value" => "Programas de cualificación profesional inicial--Preparación acceso grado medio FP", "displayed_value" => "Programas de cualificación profesional inicial--Preparación acceso grado medio FP"],
                ["stored_value" => "Programas de cualificación profesional inicial--Preparación acceso grado superior FP", "displayed_value" => "Programas de cualificación profesional inicial--Preparación acceso grado superior FP"],
                ["stored_value" => "Formación profesional--Ciclo formativo grado medio", "displayed_value" => "Formación profesional--Ciclo formativo grado medio"],
                ["stored_value" => "Formación profesional--Ciclo formativo grado superio", "displayed_value" => "Formación profesional--Ciclo formativo grado superio"],
                ["stored_value" => "Educación de personas adultas--Enseñanza básica para personas adultas--Alfabetización", "displayed_value" => "Educación de personas adultas--Enseñanza básica para personas adultas--Alfabetización"],
                ["stored_value" => "Educación de personas adultas--Enseñanza básica para personas adultas--Consolidación de conocimientos y técnicas instrumentales", "displayed_value" => "Educación de personas adultas--Enseñanza básica para personas adultas--Consolidación de conocimientos y técnicas instrumentales"],
                ["stored_value" => "Educación de personas adultas--ESPA--Nivel 1", "displayed_value" => "Educación de personas adultas--ESPA--Nivel 1"],
                ["stored_value" => "Educación de personas adultas----Nivel 2", "displayed_value" => "Educación de personas adultas----Nivel 2"],
                ["stored_value" => "Educación de personas adultas--ESPAD--Nivel 1", "displayed_value" => "Educación de personas adultas--ESPAD--Nivel 1"],
                ["stored_value" => "Educación de personas adultas----Nivel 2", "displayed_value" => "Educación de personas adultas----Nivel 2"],
                ["stored_value" => "Educación de personas adultas--Pruebas libres título general ESO", "displayed_value" => "Educación de personas adultas--Pruebas libres título general ESO"],
                ["stored_value" => "Educación de personas adultas--Pruebas libres bachillerato", "displayed_value" => "Educación de personas adultas--Pruebas libres bachillerato"],
                ["stored_value" => "Educación de personas adultas--Pruebas libres técnico", "displayed_value" => "Educación de personas adultas--Pruebas libres técnico"],
                ["stored_value" => "Educación de personas adultas--Pruebas libres técnico superior", "displayed_value" => "Educación de personas adultas--Pruebas libres técnico superior"],
                ["stored_value" => "Educación de personas adultas--Inserción o actualización laboral y profesional", "displayed_value" => "Educación de personas adultas--Inserción o actualización laboral y profesional"],
                ["stored_value" => "Educación de personas adultas--Alfabetización en lengua castellana (español para inmigrantes)", "displayed_value" => "Educación de personas adultas--Alfabetización en lengua castellana (español para inmigrantes)"],
                ["stored_value" => "Educación de personas adultas--Formación para el desarrollo personal", "displayed_value" => "Educación de personas adultas--Formación para el desarrollo personal"],
                ["stored_value" => "Educación de personas adultas--Bachillerato adultos y distancia", "displayed_value" => "Educación de personas adultas--Bachillerato adultos y distancia"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 1", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 1"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 2", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 2"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 3", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 3"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 4", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 4"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 5", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 5"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 6", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 6"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 7", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 7"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 8", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 8"],
                ["stored_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 9", "displayed_value" => "Educación de personas adultas--That's English. Enseñanza oficial de idiomas--Módulo 9"],
                ["stored_value" => "Educación de personas adultas--Ciclo formativo grado medio a distancia--Primer curso", "displayed_value" => "Educación de personas adultas--Ciclo formativo grado medio a distancia--Primer curso"],
                ["stored_value" => "Educación de personas adultas--Ciclo formativo grado medio a distancia--Segundo curso", "displayed_value" => "Educación de personas adultas--Ciclo formativo grado medio a distancia--Segundo curso"],
                ["stored_value" => "Educación de personas adultas--Ciclo formativo grado superior a distancia--Primer curso", "displayed_value" => "Educación de personas adultas--Ciclo formativo grado superior a distancia--Primer curso"],
                ["stored_value" => "Educación de personas adultas--Ciclo formativo grado superior a distancia--Segundo curso", "displayed_value" => "Educación de personas adultas--Ciclo formativo grado superior a distancia--Segundo curso"],
                ["stored_value" => "Educación de personas adultas--Aulas MENTOR", "displayed_value" => "Educación de personas adultas--Aulas MENTOR"],
                ["stored_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel básico--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel básico--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel básico--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel básico--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel intermedio--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel intermedio--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel intermedio--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel intermedio--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel avanzado--Quinto curso", "displayed_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel avanzado--Quinto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel avanzado--Sexto curso", "displayed_value" => "Enseñanzas de régimen especial--Escuela oficial de idiomas--Nivel avanzado--Sexto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado medio--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado medio--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado medio--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado medio--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado superior --Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado superior --Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado superior --Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de artes plásticas y diseño--Ciclo formativo de grado superior --Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Estudios superiores de artes plásticas y diseño--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Estudios superiores de artes plásticas y diseño--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Estudios superiores de artes plásticas y diseño--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Estudios superiores de artes plásticas y diseño--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Estudios superiores de artes plásticas y diseño--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Estudios superiores de artes plásticas y diseño--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado elemental--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Primer ciclo--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Primer ciclo--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Primer ciclo--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Primer ciclo--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Segundo ciclo--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Segundo ciclo--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Segundo ciclo--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Segundo ciclo--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Tercer ciclo--Quinto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Tercer ciclo--Quinto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Tercer ciclo--Sexto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado medio--Tercer ciclo--Sexto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Quinto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de música--Grado superior--Quinto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado elemental--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Primer ciclo--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Primer ciclo--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Primer ciclo--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Primer ciclo--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Segundo ciclo--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Segundo ciclo--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Segundo ciclo--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Segundo ciclo--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Tercer ciclo--Quinto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Tercer ciclo--Quinto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Tercer ciclo--Sexto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado medio--Tercer ciclo--Sexto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Quinto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de danza--Grado superior--Quinto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Primer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Primer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Segundo curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Segundo curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Tercer curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Tercer curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Cuarto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Cuarto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Quinto curso", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas artísticas--Enseñanzas de arte dramático--Grado superior--Quinto curso"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas deportivas--Grado medio técnico deportivo", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas deportivas--Grado medio técnico deportivo"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas deportivas--Grado superior técnico deportivo", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas deportivas--Grado superior técnico deportivo"],
                ["stored_value" => "Enseñanzas de régimen especial--Enseñanzas unversitarias", "displayed_value" => "Enseñanzas de régimen especial--Enseñanzas unversitarias"],
                ["stored_value" => "Enseñanzas de régimen especial--Programas educativos especiales", "displayed_value" => "Enseñanzas de régimen especial--Programas educativos especiales"],

            ],
            "competencia" => [
                ["stored_value" => "Competencias generales y personales--Actitud positiva al cambio", "displayed_value" => "Competencias generales y personales--Actitud positiva al cambio"],
                ["stored_value" => "Competencias generales y personales--Afectividad", "displayed_value" => "Competencias generales y personales--Afectividad"],
                ["stored_value" => "Competencias generales y personales--Autoaprendizaje a lo largo de la vida", "displayed_value" => "Competencias generales y personales--Autoaprendizaje a lo largo de la vida"],
                ["stored_value" => "Competencias generales y personales--Autoestima", "displayed_value" => "Competencias generales y personales--Autoestima"],
                ["stored_value" => "Competencias generales y personales--Autorreflexión y autoevaluación", "displayed_value" => "Competencias generales y personales--Autorreflexión y autoevaluación"],
                ["stored_value" => "Competencias generales y personales--Búsqueda de empleo", "displayed_value" => "Competencias generales y personales--Búsqueda de empleo"],
                ["stored_value" => "Competencias generales y personales--Búsqueda de información relevante", "displayed_value" => "Competencias generales y personales--Búsqueda de información relevante"],
                ["stored_value" => "Competencias generales y personales--Comunicación en lengua materna (escuchar, hablar, leer y escribir).", "displayed_value" => "Competencias generales y personales--Comunicación en lengua materna (escuchar, hablar, leer y escribir)."],
                ["stored_value" => "Competencias generales y personales--Conocimiento de los principios básicos de la naturaleza", "displayed_value" => "Competencias generales y personales--Conocimiento de los principios básicos de la naturaleza"],
                ["stored_value" => "Competencias generales y personales--Conocimiento y aprecio por la cultura y lengua de las Comunidades Autónomas", "displayed_value" => "Competencias generales y personales--Conocimiento y aprecio por la cultura y lengua de las Comunidades Autónomas"],
                ["stored_value" => "Competencias generales y personales--Conocimiento y práctica deportiva", "displayed_value" => "Competencias generales y personales--Conocimiento y práctica deportiva"],
                ["stored_value" => "Competencias generales y personales--Espíritu de empresa", "displayed_value" => "Competencias generales y personales--Espíritu de empresa"],
                ["stored_value" => "Competencias generales y personales--Expresión y compresión básica de lengua extranjera", "displayed_value" => "Competencias generales y personales--Expresión y compresión básica de lengua extranjera"],
                ["stored_value" => "Competencias generales y personales--Formulación de preguntas pertinentes", "displayed_value" => "Competencias generales y personales--Formulación de preguntas pertinentes"],
                ["stored_value" => "Competencias generales y personales--Honestidad y ética personal", "displayed_value" => "Competencias generales y personales--Honestidad y ética personal"],
                ["stored_value" => "Competencias generales y personales--Iniciativa personal", "displayed_value" => "Competencias generales y personales--Iniciativa personal"],
                ["stored_value" => "Competencias generales y personales--Interés por la expresión cultural (literatura, música, artes escénicas y plásticas)", "displayed_value" => "Competencias generales y personales--Interés por la expresión cultural (literatura, música, artes escénicas y plásticas)"],
                ["stored_value" => "Competencias generales y personales--Invención y creación", "displayed_value" => "Competencias generales y personales--Invención y creación"],
                ["stored_value" => "Competencias generales y personales--Motivación intrínseca", "displayed_value" => "Competencias generales y personales--Motivación intrínseca"],
                ["stored_value" => "Competencias generales y personales--Pensamiento crítico", "displayed_value" => "Competencias generales y personales--Pensamiento crítico"],
                ["stored_value" => "Competencias generales y personales--Perseverancia", "displayed_value" => "Competencias generales y personales--Perseverancia"],
                ["stored_value" => "Competencias generales y personales--Planificación y gestión de recursos propios (tiempo, dinero,...)", "displayed_value" => "Competencias generales y personales--Planificación y gestión de recursos propios (tiempo, dinero,...)"],
                ["stored_value" => "Competencias generales y personales--Realización de juicios informados", "displayed_value" => "Competencias generales y personales--Realización de juicios informados"],
                ["stored_value" => "Competencias generales y personales--Reconocimiento y respeto a las diferencias individuales", "displayed_value" => "Competencias generales y personales--Reconocimiento y respeto a las diferencias individuales"],
                ["stored_value" => "Competencias generales y personales--Resistencia a la ambigüedad", "displayed_value" => "Competencias generales y personales--Resistencia a la ambigüedad"],
                ["stored_value" => "Competencias generales y personales--Resistencia al fracaso", "displayed_value" => "Competencias generales y personales--Resistencia al fracaso"],
                ["stored_value" => "Competencias generales y personales--Responsabilidad", "displayed_value" => "Competencias generales y personales--Responsabilidad"],
                ["stored_value" => "Competencias generales y personales--Solución de problemas", "displayed_value" => "Competencias generales y personales--Solución de problemas"],
                ["stored_value" => "Competencias generales y personales--Uso eficiente de la información", "displayed_value" => "Competencias generales y personales--Uso eficiente de la información"],
                ["stored_value" => "Competencias generales y personales--Uso básico de las TIC", "displayed_value" => "Competencias generales y personales--Uso básico de las TIC"],
                ["stored_value" => "Competencias académicas--Acceder y aplicar el conocimiento desde diferentes disciplinas (arte, ciencias sociales, filosofía, ciencias naturales, ...)", "displayed_value" => "Competencias académicas--Acceder y aplicar el conocimiento desde diferentes disciplinas (arte, ciencias sociales, filosofía, ciencias naturales, ...)"],
                ["stored_value" => "Competencias académicas--Análisis de datos", "displayed_value" => "Competencias académicas--Análisis de datos"],
                ["stored_value" => "Competencias académicas--Aprender a aprender", "displayed_value" => "Competencias académicas--Aprender a aprender"],
                ["stored_value" => "Competencias académicas--Comprender correctamente en el lenguaje de su disciplina", "displayed_value" => "Competencias académicas--Comprender correctamente en el lenguaje de su disciplina"],
                ["stored_value" => "Competencias académicas--Conocimiento de los métodos científicos", "displayed_value" => "Competencias académicas--Conocimiento de los métodos científicos"],
                ["stored_value" => "Competencias académicas--Conocimiento de los productos y procesos tecnológicos.", "displayed_value" => "Competencias académicas--Conocimiento de los productos y procesos tecnológicos."],
                ["stored_value" => "Competencias académicas--Escuchar para entender y aprender", "displayed_value" => "Competencias académicas--Escuchar para entender y aprender"],
                ["stored_value" => "Competencias académicas--Evaluar situaciones", "displayed_value" => "Competencias académicas--Evaluar situaciones"],
                ["stored_value" => "Competencias académicas--Expresarse correctamente en el lenguaje de su disciplina (oral y escrito)", "displayed_value" => "Competencias académicas--Expresarse correctamente en el lenguaje de su disciplina (oral y escrito)"],
                ["stored_value" => "Competencias académicas--Interpretar y utilizar diferentes materiales escritos (gráficos, esquemas, cuadros, ...)", "displayed_value" => "Competencias académicas--Interpretar y utilizar diferentes materiales escritos (gráficos, esquemas, cuadros, ...)"],
                ["stored_value" => "Competencias académicas--Operaciones básicas de lecto-escritura", "displayed_value" => "Competencias académicas--Operaciones básicas de lecto-escritura"],
                ["stored_value" => "Competencias académicas--Operaciones básicas lógico-matemáticas", "displayed_value" => "Competencias académicas--Operaciones básicas lógico-matemáticas"],
                ["stored_value" => "Competencias académicas--Pensar críticamente", "displayed_value" => "Competencias académicas--Pensar críticamente"],
                ["stored_value" => "Competencias académicas--Presentación de trabajos o conclusiones escritas de forma eficiente", "displayed_value" => "Competencias académicas--Presentación de trabajos o conclusiones escritas de forma eficiente"],
                ["stored_value" => "Competencias académicas--Presentación de trabajos o conclusiones orales de forma eficiente", "displayed_value" => "Competencias académicas--Presentación de trabajos o conclusiones orales de forma eficiente"],
                ["stored_value" => "Competencias académicas--Realización de observaciones exactas e investigaciones", "displayed_value" => "Competencias académicas--Realización de observaciones exactas e investigaciones"],
                ["stored_value" => "Competencias académicas--Resolver problemas complejos (cerrados y abiertos)", "displayed_value" => "Competencias académicas--Resolver problemas complejos (cerrados y abiertos)"],
                ["stored_value" => "Competencias académicas--Sentido artístico", "displayed_value" => "Competencias académicas--Sentido artístico"],
                ["stored_value" => "Competencias académicas--Tomar decisiones", "displayed_value" => "Competencias académicas--Tomar decisiones"],
                ["stored_value" => "Competencias académicas--Utilizar las TIC de manera segura y crítica", "displayed_value" => "Competencias académicas--Utilizar las TIC de manera segura y crítica"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Animar al grupo para conseguir los mejores resultados", "displayed_value" => "Competencias sociales y de trabajo en equipo--Animar al grupo para conseguir los mejores resultados"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Comprender y contribuir a la organización de los objetivos del grupo", "displayed_value" => "Competencias sociales y de trabajo en equipo--Comprender y contribuir a la organización de los objetivos del grupo"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Comprender y trabajar dentro de la cultura del grupo", "displayed_value" => "Competencias sociales y de trabajo en equipo--Comprender y trabajar dentro de la cultura del grupo"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Dirigir discusiones de grupo", "displayed_value" => "Competencias sociales y de trabajo en equipo--Dirigir discusiones de grupo"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Ejercitar la ayuda entre los miembros del grupo para alcanzar los resultados", "displayed_value" => "Competencias sociales y de trabajo en equipo--Ejercitar la ayuda entre los miembros del grupo para alcanzar los resultados"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Persuadir", "displayed_value" => "Competencias sociales y de trabajo en equipo--Persuadir"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Respetar las maneras de pensar y las opiniones de los integrantes del grupo", "displayed_value" => "Competencias sociales y de trabajo en equipo--Respetar las maneras de pensar y las opiniones de los integrantes del grupo"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Tomar decisiones y planificar en grupo", "displayed_value" => "Competencias sociales y de trabajo en equipo--Tomar decisiones y planificar en grupo"],
                ["stored_value" => "Competencias sociales y de trabajo en equipo--Trabajar y/o aprender con otros", "displayed_value" => "Competencias sociales y de trabajo en equipo--Trabajar y/o aprender con otros"],
            ],
            "disciplina" => [
                ["stored_value" => "Desarrollo individual", "displayed_value" => "Desarrollo individual"],
                ["stored_value" => "Aprendizaje / Investigación", "displayed_value" => "Aprendizaje / Investigación"],
                ["stored_value" => "Actividades escolares", "displayed_value" => "Actividades escolares"],
                ["stored_value" => "Actividades de ocio y tiempo libre", "displayed_value" => "Actividades de ocio y tiempo libre"],
                ["stored_value" => "Enseñanza / Formación/ Evaluación/ Orientación", "displayed_value" => "Enseñanza / Formación/ Evaluación/ Orientación"],
                ["stored_value" => "Sistema Educativo", "displayed_value" => "Sistema Educativo"],
                ["stored_value" => "Contenido de la Educación --Capacidades Básicas", "displayed_value" => "Contenido de la Educación --Capacidades Básicas"],
                ["stored_value" => "Contenido de la Educación --Humanidades", "displayed_value" => "Contenido de la Educación --Humanidades"],
                ["stored_value" => "Contenido de la Educación --Ciencias Sociales y de la conducta", "displayed_value" => "Contenido de la Educación --Ciencias Sociales y de la conducta"],
                ["stored_value" => "Contenido de la Educación --Matemáticas y ciencias de la naturaleza", "displayed_value" => "Contenido de la Educación --Matemáticas y ciencias de la naturaleza"],
                ["stored_value" => "Contenido de la Educación --Ciencias aplicadas / tecnologías / técnicas", "displayed_value" => "Contenido de la Educación --Ciencias aplicadas / tecnologías / técnicas"],
                ["stored_value" => "Contenido de la Educación --Educación Física", "displayed_value" => "Contenido de la Educación --Educación Física"],
                ["stored_value" => "Contenido de la Educación --Actividades extraescolares y áreas transversales del currículo", "displayed_value" => "Contenido de la Educación --Actividades extraescolares y áreas transversales del currículo"],
                ["stored_value" => "Contenido de la Educación --Arte y Artesanía", "displayed_value" => "Contenido de la Educación --Arte y Artesanía"],
                ["stored_value" => "Contenido de la Educación --Ética / Religión / Ideología", "displayed_value" => "Contenido de la Educación --Ética / Religión / Ideología"],
                ["stored_value" => "Instalaciones / Equipo / Materiales --Infraestructura", "displayed_value" => "Instalaciones / Equipo / Materiales --Infraestructura"],
                ["stored_value" => "Instalaciones / Equipo / Materiales --Equipo", "displayed_value" => "Instalaciones / Equipo / Materiales --Equipo"],
                ["stored_value" => "Instalaciones / Equipo / Materiales --Materiales", "displayed_value" => "Instalaciones / Equipo / Materiales --Materiales"],
                ["stored_value" => "Comunicación / Información / Documentación", "displayed_value" => "Comunicación / Información / Documentación"],
                ["stored_value" => "Cultura", "displayed_value" => "Cultura"],
                ["stored_value" => "Relaciones políticas / sociales, interpersonales / Integración / Segregación", "displayed_value" => "Relaciones políticas / sociales, interpersonales / Integración / Segregación"],
                ["stored_value" => "Salud / Seguridad / Discapacidad", "displayed_value" => "Salud / Seguridad / Discapacidad"],
                ["stored_value" => "Medio Ambiente", "displayed_value" => "Medio Ambiente"],
                ["stored_value" => "Sociedad", "displayed_value" => "Sociedad"],
                ["stored_value" => "Organizaciones", "displayed_value" => "Organizaciones"],
                ["stored_value" => "Países y regiones geopolíticas", "displayed_value" => "Países y regiones geopolíticas"],
                ["stored_value" => "Lenguas modernas", "displayed_value" => "Lenguas modernas"],
            ],
            "common_lcsh" => [
                ["stored_value" => "General works", "displayed_value" => "Obras Generales"],
                ["stored_value" => "Philosophy. Psychology. Religion", "displayed_value" => "Filosofía. Psicología. Religión"],
                ["stored_value" => "Auxiliary sciences of history", "displayed_value" => "Historia - Ciencias Auxiliares"],
                ["stored_value" => "World history and history of Europe, Asia, Africa, Australia, New Zealand, etc.", "displayed_value" => "Historia (Excepto America)"],
                ["stored_value" => "History of the Americas", "displayed_value" => "Historia de América"],
                ["stored_value" => "United States local history. British America. Dutch America. French America. Latin America", "displayed_value" => "Estados Unidos (Local) y América excepto Estados Unidos"],
                ["stored_value" => "Geography. Anthropology. Recreation", "displayed_value" => "Geografía - Antropología"],
                ["stored_value" => "Social Sciences", "displayed_value" => "Ciencias sociales"],
                ["stored_value" => "Political Science", "displayed_value" => "Ciencia Politica"],
                ["stored_value" => "Law", "displayed_value" => "Derecho"],
                ["stored_value" => "Education", "displayed_value" => "Educación"],
                ["stored_value" => "Music", "displayed_value" => "Música"],
                ["stored_value" => "Fine arts", "displayed_value" => "Bellas Artes"],
                ["stored_value" => "Language and Literature", "displayed_value" => "Lengua y literatura"],
                ["stored_value" => "Science", "displayed_value" => "Ciencias"],
                ["stored_value" => "Medicine", "displayed_value" => "Medicina"],
                ["stored_value" => "Agriculture", "displayed_value" => "Agricultura - Industrias Agropecuarias"],
                ["stored_value" => "Technology", "displayed_value" => "Tecnología"],
                ["stored_value" => "Military Science", "displayed_value" => "Ciencia militar"],
                ["stored_value" => "Naval Science", "displayed_value" => "Ciencia naval"],
                ["stored_value" => "Bibliography. Library science. Information resources (general)", "displayed_value" => "Bibliotecologia y Bibliografia"],
            ],
            "range" => [
                ["stored_value" => "3 a 5 años", "displayed_value" => "3 a 5 años"],
                ["stored_value" => "6 a 9 años", "displayed_value" => "6 a 9 años"],
                ["stored_value" => "10 a 13 años", "displayed_value" => "10 a 13 años"],
                ["stored_value" => "14 a 17 años", "displayed_value" => "14 a 17 años"],
                ["stored_value" => "18 a 22 años", "displayed_value" => "18 a 22 años"],
                ["stored_value" => "22 a 25 años", "displayed_value" => "22 a 25 años"],
                ["stored_value" => "26 a 30 años", "displayed_value" => "26 a 30 años"],
                ["stored_value" => "31 a 40 años", "displayed_value" => "31 a 40 años"],
                ["stored_value" => "50 a 60 años", "displayed_value" => "50 a 60 años"],
                ["stored_value" => "61 y más", "displayed_value" => "61 y más"],
            ],
            "version" => [
                ["stored_value" => "1", "displayed_value" => "1"],
                ["stored_value" => "2", "displayed_value" => "2"],
                ["stored_value" => "3", "displayed_value" => "3"],
                ["stored_value" => "4", "displayed_value" => "4"],
                ["stored_value" => "5", "displayed_value" => "5"]
            ],
            "asignaturas" => Subject::get()->map(function ($subject) {
                return [
                    'stored_value' => "$subject->key $subject->title",
                    'displayed_value' => "$subject->key $subject->title"
                ];
            })->toArray()
        ]);

        if ($name) {
            return $collection[$name];
        }

        return $collection;
    }
}
